=begin
problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=end




def fib(n) #takes number of terms as argument (just make sure this is larger than limit)
  array = [0, 1]
  fib_sequence = [0, 1]
  i = 2
  (n-2).times do
    array[i] = array[i-1] + array[i-2]
    if array[i] <= 4000000   #change this limit to whatever you want
      fib_sequence << array[i]
      i += 1
    end
  end
  evens = []
  fib_sequence.each { |x| evens << x if x % 2 == 0 } #to sum evens only
  print evens
  total = evens.inject(0, :+)
end

#answer = 4613732

#better method doesn't rely on guessing n needed

def fin
  array = [0, 1]
  fib = [0, 1]
  i = 2
  array[i] = array[i-1] + array[i-2]
  while array[i] <= 4_000_000
    fib << array[i]
    i += 1
    array[i] = array[i-1] + array[i-2]
  end
  evens = Array.new
  fib.each { |x| evens << x if x % 2 == 0 }
  print evens
  total = evens.inject(0, :+)
end

#even better method (faster, less memory intensive and doesn't keep the entire fib sequence in memeory):

def fin
array = [0, 1]
evens = Array.new
array[2] = array[0] + array[1]
while array[2] <= 4_000_000
  evens << array[2] if array[2] % 2 == 0
  array[0] = array [1]
  array [1] = array[2]
  array[2] = array[0] + array[1]
end
total = evens.inject(0, :+)
end
