=begin

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=end




def fib(n) #takes number of terms as argument
  array = [0, 1]
  fib_sequence = [0, 1]
  i = 2
  (n-2).times do
    array[i] = array[i-1] + array[i-2]
    if array[i] <= 1000000000000000000000   #change this limit to whatever you want
      fib_sequence << array[i]
      i += 1
    end
  end
  evens = []
  fib_sequence.each { |x| evens << x if x % 2 == 0 } #to sum evens only
  total = evens.inject(0, :+)
end
