/*
problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
var fib_sequence = [0, 1];
var evens = [];
var array = [0, 1];
var sum = 0;
var fib = function(n) {
  for (i = 2; i <= n; i++) {
    array[i] = array[i-1] + array[i-2];
    if (array[i] <= 4000000) {  //change this limit to whatever you want
      fib_sequence.push(array[i]);
    }
  }
  for (i = 0; i < fib_sequence.length; i++) {
    if (fib_sequence[i] % 2 === 0) {
      evens.push(fib_sequence[i])
    }
  }
  for (i = 0; i < evens.length; i++) {
    sum += evens[i];
  }

}
